version: 2.1

orbs: 
  gh: circleci/github-cli@2.1.0
  
jobs:
  build:
    docker: 
      - image: cimg/base:edge
    steps:
      - checkout
      - gh/setup
      - run:
          name: Determine PR target branch
          command: |
            HEAD_BRANCH=$(gh pr view $CIRCLE_PULL_REQUEST --json headRefName --jq '.headRefName')
            TARGET_BRANCH=$(gh pr view $CIRCLE_PULL_REQUEST --json baseRefName --jq '.baseRefName')
            echo "$HEAD_BRANCH -> $TARGET_BRANCH"
            if [[ $HEAD_BRANCH == "dev" -a $TARGET_BRANCH == "main"]] then
              echo "Run integration tests"
            else
              echo "Exit Job"
            fi
            
workflows:
  github_cli:
    jobs:
      - build
