version: 2.1

orbs: 
  gh: circleci/github-cli@2.1.0
  
jobs:
  build:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - gh/setup
      - run: echo "test"

workflows:
  github_cli:
    jobs:
      - build
      
